#!/bin/bash
# Plasma Shield Agent Lockdown Script
#
# This script configures an agent VPS to route ALL traffic through
# the Plasma Shield router. The agent will be unable to reach the
# internet directly.
#
# Run this on the agent VPS (NOT on the shield router).
#
# Usage:
#   curl -fsSL https://get.plasmashield.dev/lockdown | bash -s -- \
#     --shield-ip <ROUTER_IP> \
#     --agent-token <TOKEN>

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}[plasma-shield]${NC} $1"; }
warn() { echo -e "${YELLOW}[plasma-shield]${NC} $1"; }
error() { echo -e "${RED}[plasma-shield]${NC} $1" >&2; }

# Parse arguments
SHIELD_IP=""
AGENT_TOKEN=""
SHIELD_PORT="8443"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --shield-ip)
            SHIELD_IP="$2"
            shift 2
            ;;
        --agent-token)
            AGENT_TOKEN="$2"
            shift 2
            ;;
        --shield-port)
            SHIELD_PORT="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        *)
            error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate required arguments
if [[ -z "$SHIELD_IP" ]]; then
    error "Missing required argument: --shield-ip"
    exit 1
fi

if [[ -z "$AGENT_TOKEN" ]]; then
    error "Missing required argument: --agent-token"
    exit 1
fi

log "Plasma Shield Agent Lockdown"
log "Shield IP: $SHIELD_IP"
log "Shield Port: $SHIELD_PORT"
log "Dry run: $DRY_RUN"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root"
    exit 1
fi

# Test connectivity to shield
log "Testing connectivity to shield router..."
if ! curl -sf --connect-timeout 5 "http://${SHIELD_IP}:${SHIELD_PORT}/health" > /dev/null 2>&1; then
    warn "Could not connect to shield router. Continuing anyway..."
fi

# Backup current iptables rules
log "Backing up current iptables rules..."
if [[ "$DRY_RUN" == "false" ]]; then
    iptables-save > /root/iptables-backup-$(date +%Y%m%d-%H%M%S).rules
fi

# Configure iptables
log "Configuring iptables firewall..."

IPTABLES_RULES=$(cat <<EOF
# Flush existing rules
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT DROP [0:0]

# Allow loopback
-A OUTPUT -o lo -j ACCEPT
-A INPUT -i lo -j ACCEPT

# Allow established connections
-A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow traffic to shield router ONLY
-A OUTPUT -d ${SHIELD_IP} -j ACCEPT

# Allow SSH (so you don't lock yourself out)
-A INPUT -p tcp --dport 22 -j ACCEPT
-A OUTPUT -p tcp --sport 22 -j ACCEPT

# Log blocked traffic (optional, can be noisy)
# -A OUTPUT -j LOG --log-prefix "PLASMA-BLOCKED: "

# Drop everything else (default policy)
COMMIT
EOF
)

if [[ "$DRY_RUN" == "true" ]]; then
    log "DRY RUN - Would apply these rules:"
    echo "$IPTABLES_RULES"
else
    echo "$IPTABLES_RULES" | iptables-restore
    log "iptables rules applied"
fi

# Save iptables rules to persist across reboots
if [[ "$DRY_RUN" == "false" ]]; then
    if command -v netfilter-persistent &> /dev/null; then
        netfilter-persistent save
    elif [[ -f /etc/debian_version ]]; then
        iptables-save > /etc/iptables/rules.v4
    elif [[ -f /etc/redhat-release ]]; then
        service iptables save
    fi
    log "iptables rules persisted"
fi

# Store agent token for the OpenClaw integration
log "Storing agent configuration..."
if [[ "$DRY_RUN" == "false" ]]; then
    mkdir -p /etc/plasma-shield
    cat > /etc/plasma-shield/agent.yaml <<EOF
# Plasma Shield Agent Configuration
# Generated by lockdown.sh

shield_ip: ${SHIELD_IP}
shield_port: ${SHIELD_PORT}
agent_token: ${AGENT_TOKEN}
EOF
    chmod 600 /etc/plasma-shield/agent.yaml
    log "Agent configuration stored at /etc/plasma-shield/agent.yaml"
fi

# Configure environment for proxy
log "Configuring proxy environment..."
if [[ "$DRY_RUN" == "false" ]]; then
    cat > /etc/profile.d/plasma-shield.sh <<EOF
# Plasma Shield Proxy Configuration
export HTTP_PROXY="http://${SHIELD_IP}:${SHIELD_PORT}"
export HTTPS_PROXY="http://${SHIELD_IP}:${SHIELD_PORT}"
export http_proxy="http://${SHIELD_IP}:${SHIELD_PORT}"
export https_proxy="http://${SHIELD_IP}:${SHIELD_PORT}"
export NO_PROXY="localhost,127.0.0.1,${SHIELD_IP}"
EOF
    chmod 644 /etc/profile.d/plasma-shield.sh
    log "Proxy environment configured"
fi

log ""
log "============================================"
log "  LOCKDOWN COMPLETE"
log "============================================"
log ""
log "This agent can now ONLY reach the internet through"
log "the Plasma Shield router at ${SHIELD_IP}."
log ""
log "To verify, try: curl https://google.com"
log "It should work (via proxy) or timeout if shield is not running."
log ""
log "To undo, restore from backup:"
log "  iptables-restore < /root/iptables-backup-*.rules"
log ""
